version: '3.8'

services:
  web:
    build: ./web
    ports:
      - "80:5000"
    volumes:
      - ./pdfs:/app/pdfs
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: finalexamdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: